In [1]:
import pandas as pd
landmark = pd.DataFrame({'name':['광화문','호미곶', '첨성대'], 
                         'location':['서울 종로구 사직로 161', 
                                     '경북 포항시 남구 호미곶면 대보리 150',
                                     '경북 경주시 인왕동 839-1']})
landmark['location'].str[3:6]

0    종로구
1    포항시
2    경주시
Name: location, dtype: object

In [4]:
landmark['location'].str.split(" ", expand=True)

    0    1    2      3     4     5
0  서울  종로구  사직로    161  None  None
1  경북  포항시   남구   호미곶면   대보리   150
2  경북  경주시  인왕동  839-1  None  None

In [3]:
landmark['loc_1'] = landmark['location'].str.split(" ").str[0]
landmark

  name                location loc_1
0  광화문          서울 종로구 사직로 161    서울
1  호미곶  경북 포항시 남구 호미곶면 대보리 150    경북
2  첨성대        경북 경주시 인왕동 839-1    경북

In [4]:
landmark['location'].str.startswith('서울')

0     True
1    False
2    False
Name: location, dtype: bool

In [5]:
landmark['location'].str.endswith('1')

0     True
1    False
2     True
Name: location, dtype: bool

In [6]:
landmark['location'].str.contains('1')

0    True
1    True
2    True
Name: location, dtype: bool