In [7]:
import pandas as pd

score = {'학년':[1, 1, 1, 1, 2, 2], 
         '반':['A', 'A', 'B', 'B', 'C', 'C'], 
         '성별':['여자', '남자', '여자', '남자', '여자', '남자'],
         '성적': [76, 88, 85, 72, 68, 70]}

score = pd.DataFrame(score)
score

   학년  반  성별  성적
0   1  A  여자  76
1   1  A  남자  88
2   1  B  여자  85
3   1  B  남자  72
4   2  C  여자  68
5   2  C  남자  70

#### 피벗테이블의 컬럼은 '범주형 변수' 사용

In [8]:
score = score.pivot_table(index=['학년', '반'], columns='성별', values='성적')
score

성별    남자  여자
학년 반
1  A  88  76
   B  72  85
2  C  70  68

#### 멜트: 피벗테이블의 반대개념으로 컬럼으로 나열된 자료를 압축

In [12]:
score.reset_index().melt(id_vars=['학년','반'], var_name='성별', value_name='성적')

   학년  반  성별  성적
0   1  A  남자  88
1   1  B  남자  72
2   2  C  남자  70
3   1  A  여자  76
4   1  B  여자  85
5   2  C  여자  68

In [4]:
import numpy as np
score.apply(np.sqrt, axis=0)

성별          남자        여자
학년 반
1  A  9.380832  8.717798
   B  8.485281  9.219544
2  C  8.366600  8.246211

In [5]:
score.apply(np.max, axis=0)

성별
남자    88
여자    85
dtype: int64

In [6]:
def plus_five(val):
    return val + 5

score.apply(plus_five)

성별    남자  여자
학년 반
1  A  93  81
   B  77  90
2  C  75  73

In [7]:
from math import ceil
def class_avg(df):
    return ceil((df['남자'] + df['여자'])/2)

score.apply(class_avg, axis=1)

학년  반
1   A    82
    B    79
2   C    69
dtype: int64

In [8]:
score['남자'].map(lambda x: x + 5)

학년  반
1   A    93
    B    77
2   C    75
Name: 남자, dtype: int64